### PR TITLE
Fix tag pull request owner when /change or /approve command is called

### LINKED ISSUE #21: comando `/change` marcando pessoa errada
aparentemente no comando `/change` as vezes o bot marca outra pessoa em vez de marcar quem abriu a thread, necessário corrigir isso 

image

### PR DESCRIPTION
**Pull request by aalmeida00**
Closes #21

<details> 
  <summary>
    <b>Feature</b>
  </summary>

N/A

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

### CODE REVIEW

File: src/commands/approve/approve.ts [hunk 1]
```diff
@@ -10,16 +10,36 @@ export const data = new SlashCommandBuilder()
...
   if (!channel || channel.type !== ChannelType.PublicThread) {
     return
   }
 
   const members = await channel.members.fetch()
+  const pullOwner = pullRequestOwner ? members.get(pullRequestOwner) : null
 
-  const [pullOwner] = members.map((member) => member)
+  const replyContent = `❌ Necessário realizar mudanças no código, ${
+    pullOwner ? pullOwner.user : 'Unknown user'
```
Comment (hxsggsz) [inline src/commands/approve/approve.ts:41]: acho que da pra juntar esses dois ternários no primeiro, talvez o valor inicial dessa variavel ser `unknown user`  ou o else do primeiro ternário ser `unknown user`

**Review by hxsggsz — CHANGES_REQUESTED** [review]

**Review by k1nha — APPROVED** [review]

**Review by hxsggsz — APPROVED** [review]

**Review by k1nha — APPROVED** [review]
