### PR TITLE
fix bug when someone select a revisor twice the other commands stop working

### LINKED ISSUE #42: When user selects someone to review twice the other commands stop work

### PR DESCRIPTION
**Pull request by hxsggsz**
Closes #42 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

fix bug when someone select a revisor twice the other commands stop working because it was pinning the message twice

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
when someone select a revisor twice the other commands stop working 

- **Cause**
because the bot takes the pinned message to use as reference for other commands and when you select someone twice it was pinning the message twice and the pin flow is broken

- **Solution**
now the message with the information necessary is only pinned if dont have the same message pinned before
</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [ ] Tests created
</details>

### CODE REVIEW

File: src/commands/pulls/pulls.ts [hunk 1]
```diff
@@ -125,7 +125,16 @@ export async function execute(interaction: CommandInteraction, client: Client) {
         components: [row],
       })
 
-      await pinMessage(thread)
+      const messages = await thread.messages.fetchPinned()
+
+      const messageInfo = messages.at(0)
+      console.log(messageInfo)
```
Comment (k1nha) [inline src/commands/pulls/pulls.ts:131]: e esse console aqui

**Review by k1nha — APPROVED** [review]

File: src/commands/pulls/pulls.ts (hunk 1 above)
Comment (aalmeida00) [reply src/commands/pulls/pulls.ts:131]: Acredito que nao tem como ficar undefined nao, só se for em thread MUUUITO antiga, a maioria já morreu.

**Review by aalmeida00 — APPROVED** [review]

**Review by k1nha — APPROVED** [review]

**Review by PiluVitu — APPROVED** [review]
